### ISSUE TITLE
Incorrect link for Table 20?

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#43]
### Contact Details

sarahpogue@gmail.com

### Your suggestion.

In the List of Tables in the alg doc, the link for Table 20 is: https://github.com/holos-aafc/Holos/blob/main/H.Core/Providers/Feed/DietProvider.cs
However I am not sure this is linking to the correct table. Clicking on "Link" should take the user to the table "Examples of NEmf content of typical diets fed to cattle for estimation of dry matter intake (IPCC 2019, Table 10.8a)" - please see attached file for the correct table.
[Table 20_AlgDoc.docx](https://github.com/holos-aafc/Holos/files/12253901/Table.20_AlgDoc.docx)

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by hafzaal** [comment]
I think the reason it links to that file is because of the code starting at line 427. The link to that line is:

https://github.com/holos-aafc/Holos/blob/a30b5d2682c8b6c9b96ec31069a04e006e2ab9e0/H.Core/Providers/Feed/DietProvider.cs#L427

And then the values from the table are on lines:

448 => DietType = DietType.LowEnergyAndProtein
446 => DietaryNetEnergyConcentration = 4.5

473 => DietType = DietType.MediumEnergyAndProtein
493 => DietaryNetEnergyConcentration = 6

500 =>  DietType = DietType.HighEnergyAndProtein,
520 => DietaryNetEnergyConcentration = 7.0

If you feel that this seems correct then maybe we can directly link to line 427 of that file so that its easier for people to find where the table begins?

**Comment by sarahp1980** [comment]
Thanks Hassan! I thought the correct values might be in there somewhere - if that link could take the user directly to the relevant lines, that would be great.

**Comment by sarahp1980** [comment]
Thanks Hassan. I've updated the link in the alg doc.
