### ISSUE TITLE
Zero estimates for swine GHGs

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#46]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expected Holos to calculate GHG emissions for specific swine groups, based on the input data.

### Actual Behaviour

For certain swine groups, Holos does not appear to have correctly calculate various estimates. These points relate to the “Manitoba 1000 sow FW 1995.json” farm file (available here: https://drive.google.com/file/d/1HBxxLOo7G27IEQRwAsPDFNdMGrG9ipwx/view?usp=sharing), and to the Excel version of this file (attached). **In the Excel file, you can look at the ‘EmissionsSummaryTables”**, which compares the Holos and Excel outputs – all cell numbers below refer to this worksheet in the Excel file.
•	In the farm file, although the user specified a yearly enteric CH4 rate of 2.00 kg head-1 year-1 for sows in the "Wean to rebreeding" management period, the final emissions estimates are zero for each month of the year for this animal group – see Cell G7;
•	In the farm file, for both custom and default diets, the “Total digestible nutrient” value is always zero, under Additional information;
•	In the Holos outputs, the Cexcretion estimate for ‘Gilts’ is slightly higher than the Excel estimate, although this may just be due to a rounding error – see Cell G14;
•	Animals in the "Wean to rebreeding" management period are fed the 'gilt/gestation' diet but, as for enteric CH4 emissions, the Cexcretion estimates for this animal group are zero – see Cell G17. The same is true for Nexcretion estimates, and all GHG emissions estimates for this group are zero;
•	Although in the attached farm file the user specified the application of straw bedding at a rate of 0.79 kg per head per day for Maintenance boars and AI boars, Cbedding is zero on the Manure Management screen in Holos for these animal groups - see Cell G29-30;
•	In the swine interface > Housing tab > Additional information, for Sow groups the “Activity coefficient of feeding situation” and “Maintenance coefficient” are detailed under the bedding application calculator, but not for the other swine groups. These coefficients can be removed from these screens as they are not relevant for swine.

[HolosV4ModelTesting_FroeseSwine_MBFarm_FINAL.xlsx](https://github.com/holos-aafc/Holos/files/12337570/HolosV4ModelTesting_FroeseSwine_MBFarm_FINAL.xlsx)

### Describe the Issue & Steps to Reproduce

To recreate these issues, the input data were simply entered as normal into the interface.

### Error Message

n/a

### Holos Version Number

4.0.0.473

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by aaron-mcpherson** [comment]
1) In the 'wean to rebreeding' management period, the user must specify a production stage other than 'weaning' otherwise Holos assumes the young animals are not producing emissions (i.e. that these animals are piglets, etc.)
2) TDN has been removed for swine diets since swine diet ingredients do not include TDN information.
3) In the Excel sheet, I have verified that the DMI is 2.55, Cfeed, Cdigestibility, and number of animals are correct. The only difference is Holos calculates the carbon excreted as 6.1964999999999995 per day. This seems to be a rounding difference as you noted.
4) This is related to #1 
5) This has been fixed in version 4.0.0.476. Some bedding types not valid for swine animals have been removed. To update the bedding results, the bedding type will have to be changed from 'none' to one of the other choices to initiate the new calculation
6) Activity & maintenance coefficients has been removed for sows since these values are not needed for this group
