### ISSUE TITLE
Error when Running CLI using GUI files

### ISSUE THREAD

**Issue by ramsaym** [holos-aafc/Holos#56]
### Contact Details

matt.ramsay@peifa.ca

### Expected Behaviour

Trying to complete the processing via CLI, Hangs up on this error. 

### Actual Behaviour

![image](https://github.com/holos-aafc/Holos/assets/48220108/aa3da7a4-9fce-4c0e-923b-6a439fe71ebe)

### Describe the Issue & Steps to Reproduce

1. run cli using GUI generated farms 
2. exception caught from line 931 in H.Core or thereabouts  (see image above) 

### Error Message

see above image

### Holos Version Number

latest

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by aaron-mcpherson** [comment]
@ramsaym can you link to the farm file used in this run (you'll have to change the file extensions from .json to .txt to upload attachements). Thanks

**Comment by ramsaym** [comment]
[ocf .zip](https://github.com/holos-aafc/Holos/files/12666612/ocf.zip)

I had to compress it to stay under 25MB. One thing I noticed is that there were older folder structures (farm files) from older CLI versions. When I removed them and left only the .json file it seemed to process, but I have only repeated once so will see if that fixed it. This .json may not be the issue. I got a folder structure timestamped accordingly (files were written) and it looks like all the GHG is in the field.csv files?

**Comment by aaron-mcpherson** [comment]
@ramsaym I also ran the file you've sent me named "ocf". The CLI executed from start to finish without generating the error above. It might be due to Holos processing the generated field input files from an older version of the CLI. If you remove those field files (folders) and re-run the CLI so that it generates a 'fresh' set of field input files it should run without issue as you also noted.

The field specific outputs from the CLI run are in the "Outputs" folder and then in the "Fields" subfolder.

**Comment by ramsaym** [comment]
Ok. It seems to  work for me when I start with fresh files. In fact, going right from the GUI output .json to the end product seems to be the most consistent. Able to generate batch jobs now. Thanks for the help on this.
